// src/components/help/SettingsHelp.jsx
import HelpPanel, { Section, Step, Field, Note } from '../HelpPanel'

export default function SettingsHelp({ onClose }) {
  return (
    <HelpPanel title="Settings — Help" onClose={onClose}>

      <Section title="What is this page?">
        Settings controls company-wide configuration that applies across the entire
        KSR MIS — logo, bank details, office address, system limits, and Google Drive
        integration. Changes here reflect immediately on all quotations, receipts,
        and system behaviour.
      </Section>

      <Section title="Company & Bank Details">
        These details appear on every quotation and receipt generated by the system.
        <div style={{marginTop:'10px',display:'flex',flexDirection:'column',gap:'5px'}}>
          <Field name="Logo" desc="Uploaded image shown at the top of every quotation and receipt. Recommended size: 300×150px, PNG with transparent background." />
          <Field name="Account Holder Name" desc="The name printed on quotations e.g. KSR REALTY. Appears as the payee name on payment instructions." />
          <Field name="Bank Name" desc="Bank where customers should transfer payments e.g. Indian Bank." />
          <Field name="Account No." desc="KSR's bank account number shown on quotations." />
          <Field name="IFSC Code" desc="Bank branch IFSC for NEFT/RTGS transfers. Shown on quotations." />
          <Field name="Office Address" desc="One office per line. Printed in the footer of every quotation and receipt. Include all branch addresses if needed." />
        </div>
        <Note>Click Save Settings after making any changes. Changes apply to all future documents — existing printed documents are not affected.</Note>
      </Section>

      <Section title="Uploading the logo">
        <Step number="1" text="Click Upload logo (or Replace logo if one already exists)." />
        <Step number="2" text="Select an image file (PNG, JPG, or SVG)." />
        <Step number="3" text="Wait for the upload to complete — you'll see a preview." />
        <Step number="4" text="Click Save Settings to apply the new logo." />
        <Note>The logo is stored in Supabase Storage under the company-assets bucket. If upload fails with a bucket error, ask your system administrator to create the bucket first.</Note>
      </Section>

      <Section title="System Configuration">
        <div style={{display:'flex',flexDirection:'column',gap:'5px'}}>
          <Field name="Maximum Write-Off Amount" desc="Sets the upper limit for the Write-Off button in BookingDetail. If the landowner balance exceeds this amount, the write-off button is blocked. Default: ₹1,000." />
          <Field name="Excess Payment — Ignore Threshold" desc="In the Excess Payments page, any excess at or below this amount shows an Ignore option instead of requiring a full settlement. Useful for rounding differences like ₹7 or ₹15. Default: ₹500." />
        </div>
        <Note>Both limits apply system-wide across all projects and bookings.</Note>
      </Section>

      <Section title="Google Drive Integration">
        Google Drive is used to store and retrieve project documents (sale deeds,
        layout plans, NOCs etc.) uploaded in the Documents section.

        <div style={{marginTop:'10px',display:'flex',flexDirection:'column',gap:'6px'}}>
          {[
            ['Connected','A green tick shows the Drive account is connected. Documents can be uploaded and imported.'],
            ['Not connected','An amber warning shows. Documents cannot be uploaded until Drive is connected.'],
            ['Reconnect','Use this if the connection expires or if you need to switch to a different Google account.'],
          ].map(([status, desc], i) => (
            <div key={i} style={{background:'#f8fafc',borderRadius:'6px',padding:'8px 10px',border:'1px solid #e2e8f0'}}>
              <div style={{fontWeight:600,color:'#1B2A4A',fontSize:'12px'}}>{status}</div>
              <div style={{color:'#64748b',fontSize:'11px',marginTop:'2px'}}>{desc}</div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Connecting Google Drive">
        <Step number="1" text="Click Connect Google Drive." />
        <Step number="2" text="You are redirected to Google — sign in with legal.ksrrealty@gmail.com." />
        <Step number="3" text="Click Allow to grant KSR MIS access to Drive." />
        <Step number="4" text="You are redirected back to Settings — a green tick confirms the connection." />
        <Note>Always use legal.ksrrealty@gmail.com for the Drive connection — this is the account that owns the KSR document folders. Connecting a different account will break the folder links.</Note>
      </Section>

      <Section title="Frequently asked questions">
        <div style={{display:'flex',flexDirection:'column',gap:'10px'}}>
          {[
            [
              'Will changing the bank details update old quotations?',
              'No — changes apply only to new quotations and receipts generated after saving. Already-printed or already-sent documents are not changed.'
            ],
            [
              'The logo is showing on the settings page but not on quotations — why?',
              'You may have uploaded the logo but not clicked Save Settings. Always click Save Settings after uploading to commit the change.'
            ],
            [
              'Google Drive connection keeps expiring — what do I do?',
              'Click Reconnect with a different account (or the Connect button if disconnected) and sign in again. The system stores a refresh token that should keep the connection alive, but it may expire if unused for a long time.'
            ],
            [
              'Who should have access to Settings?',
              'Only KSR management or the system administrator should access Settings. Changing bank details or write-off limits affects all users and all documents.'
            ],
            [
              'Can I have different bank accounts for different projects?',
              'Not currently — one bank account is shown on all quotations. If this is needed, contact Carob Technologies to configure project-level bank details.'
            ],
          ].map(([q, a], i) => (
            <div key={i}>
              <div style={{fontWeight:600,color:'#1B2A4A',fontSize:'12px',marginBottom:'3px'}}>{q}</div>
              <div style={{color:'#64748b',fontSize:'12px'}}>{a}</div>
            </div>
          ))}
        </div>
      </Section>

    </HelpPanel>
  )
}
